version = 1
SPDX-PackageName = "gb-dispatch-model"
SPDX-PackageSupplier = "Open Energy Transition gGmbH"
SPDX-PackageDownloadLocation = "https://github.com/open-energy-transition/gb-dispatch-model"

[[annotations]]
path = [
    "doc/gb-model/**",
]
SPDX-FileCopyrightText = "gb-dispatch-model contributors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = [
    "envs/**/*.pin.txt",
]
SPDX-FileCopyrightText = "gb-dispatch-model contributors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "data/**",
    "doc/configtables/*",
    "doc/data.csv",
    "doc/img/*",
    "test/test_data/*",
]
SPDX-FileCopyrightText = "The PyPSA-Eur Authors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = [
    ".github/**",
    "borg-it",
    "envs/*.lock.yaml",
    "matplotlibrc",
]
SPDX-FileCopyrightText = "The PyPSA-Eur Authors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "report/**",
]
SPDX-FileCopyrightText = "Open Energy Transition gGmbH"
SPDX-License-Identifier = "MIT"
